### ISSUE TITLE
New Api for updating user information

### ISSUE THREAD

**Issue by pedromcunha** [dmonay/okra#11]
There needs to be a new Api for updating the user information. This information will come from the front end and should consist of these nodes:

```json
{
   userName: 'someUser'
   organizations: [],
   googleAuthInfo: {}
}
```
Note that the googleAuthInfo will be information provided by google auth, if this ever changes we just replace it. I think these are all the parameters that we'll use in regards to authentication and user information. If you think we need anything else we can discuss.

**Comment by dmonay** [comment]
we decided to use the /register endpoint for now
